# Copyright (c) 2023-2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=file", "--version=14"]
      - id: clang-tidy
        args:
          [
            "--version=14",
            "--checks=-*",
            "--config-file=.clang-tidy",
            "--format-style=file",
          ]
      - id: cpplint
        args: ["--recursive"]
      - id: cppcheck
        args: [
            "--project=build/compile_commands.json",
            "--language=c++",
            "--std=c++17",
            "--error-exitcode=1",
            "--enable=all",
            "--inline-suppr",
            "--suppress=noExplicitConstructor",
            "--suppress=missingInclude",
            "--suppress=unusedFunction",
            "--suppress=uninitMemberVar",
            "--suppress=unmatchedSuppression",
            # suppress all warnings for generated code
            "--suppress=*:build*/*",
            "--suppress=*:app/vehicle_model/*",
            "--suppress=*:examples/vehicle_model/*",
          ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        files: '.*\.(py|pyi|yaml|yml|sh)$'
        exclude: "reinstall-cmake.sh"
        args:
          - --license-filepath
          - license_header.txt
          - --comment-style
          - "#"
          - --use-current-year
          - --allow-past-years
          - --skip-license-insertion-comment=This file is maintained by velocitas CLI, do not modify manually.
      - id: insert-license
        files: '.*\.(cpp|c|cc|h)$'
        exclude: '.*\.(pb.cpp|pb.c|pb.cc|pb.h)$'
        args:
          - --license-filepath
          - license_header.txt
          - --comment-style
          - /**| *| */
          - --use-current-year
          - --allow-past-years
          - --skip-license-insertion-comment=This file is maintained by velocitas CLI, do not modify manually.
      - id: insert-license
        files: "Dockerfile.*|CMakeLists.txt"
        args:
          - --license-filepath
          - license_header.txt
          - --comment-style
          - "#"
          - --use-current-year
          - --allow-past-years
          - --skip-license-insertion-comment=This file is maintained by velocitas CLI, do not modify manually.
